#ifndef BITCOIN_CHAINPARAMSSEEDS_H
#define BITCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the waifu network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */

static const uint8_t chainparams_seed_main[] = {
    0x01,0x04,0xa5,0x16,0x5a,0x81,0x1e,0x61,
    0x01,0x04,0xa5,0x16,0x54,0x74,0x1e,0x61,
    0x01,0x04,0xa5,0x16,0x58,0x5c,0x1e,0x61,
};

static const uint8_t chainparams_seed_test[] = {
};

#endif // BITCOIN_CHAINPARAMSSEEDS_H
